### ISSUE TITLE
Link to Docs in plug-in info page within admin interface does not work.

### ISSUE THREAD

**Issue by Eihrister** [OleVik/grav-plugin-nomnoml-uml-diagrams#3]
Hello!

When going to /admin/plugins/nomnoml-uml-diagrams, it states the following as link to the Docs:

https://github.com/OleVik/grav-plugin-nomnoml-uml-diagrams/blob/develop/README.md

That link 404's.

Kind regards,

Eihrister

**Comment by OleVik** [comment]
Solved by https://github.com/OleVik/grav-plugin-nomnoml-uml-diagrams/releases/tag/v1.1.1.
